### ISSUE TITLE
Make it possible to disable email sending on dev systems

### ISSUE THREAD

**Issue by rfrovarp** [NDSU-Information-Technology/international-capstone-exchange#1]
This should be done via a JNDI configuration that when enabled, turns off the whole email sending system. Likely most developers don't have a development system from which they are running an SMTP server that can send email. We want the flag to turn it off, so that we don't need to add a flag to our production systems.

**Comment by TimMarshalHunter** [comment]
I've been struggling to find info on how to add flags as VM arguments. What I have found seems to have something to do with editing a start.ini file located... somewhere. Another idea I had was to just add another parameter to the EmailConfig in the jetty-env.xml file. Would this work for implementation, or should I keep digging for info on creating flags?

**Comment by rfrovarp** [comment]
It needs to be in the JNDI, which is jetty-env.xml for the most part. Looks like we have a comp/env/bean/emailconf which has a from address value in it. That probably just needs a boolean value added to it to disable (with enable being the default so production doesn't need to change). So the boolean is probably a disable, so that the Java default of false makes sense.

**Comment by TimMarshalHunter** [comment]
Ah, yeah. That's what I was thinking of with my previous comment. Was going to add another parameter to that class exactly since it made the most sense there. Thought the original post's idea was to add another flag under the VM arguments in the run configuration or something. I'll add another parameter under the emailconf in the jetty-env.xml.
