### ISSUE TITLE
Allow admins to change log level

### ISSUE THREAD

**Issue by rfrovarp** [NDSU-Information-Technology/international-capstone-exchange#14]
Admins should be able to change the log level of the application during runtime. It is extremely beneficial to be able to kick the Cayenne part of the logs to info to log actual production requests when someone is having trouble. The root and application loggers are also handy to change. There is no need to persist these changes, as we don't need to keep them through restarts.

**Comment by TimMarshalHunter** [comment]
Have a tentative implementation for this. Not sure if it covers all you're looking for though since I'm not very familiar with how the logger works. The implementation works by changing the log4j.properties file and reapplying it's configuration during runtime. Will need to know if this is an acceptable approach and if so which properties should be adjustable. Also whether one selection box is fine to be applied to all or whether separate selection boxes should be added for each property.

**Comment by TimMarshalHunter** [comment]
Done.
